app:
    resource: '@AppBundle/Controller/'
    type: annotation

list:
    path:      /list/{what}/{howMany}
    defaults:  { _controller: AppBundle:Default:list, what: albums, howMany: 100 }
    requirements:
        howMany: '\d+'