app:
    resource: '@AppBundle/Controller/'
    type: annotation

list:
    path:      /%app.route_prefix%/list/{what}/{howMany}
    defaults:  { _controller: AppBundle:Default:list, what: albums, howMany: 100 }
    requirements:
        howMany: '\d+'
        _locale: '%app.locales%'